services:
    prometheus:
        image: prom/prometheus
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus_data/prometheus.yml:/etc/prometheus/prometheus.yml
        command:
          - '--config.file=/etc/prometheus/prometheus.yml'

    prod:
      build:
        context: ./
        dockerfile: Dockerfile
      depends_on:
        - prometheus
        - grafana
        - db
      ports:
        - 8000:8000
  
    grafana:
      image: grafana/grafana
      container_name: grafana
      ports:
        - 3000:3000

    db:
        image: postgres:15-alpine
        expose:
          - "4596"
        volumes:
          - ./db/postgresql:/var/lib/postgresql
        command: -p 4596
        ports:
          - "4596:4596"
        env_file:
          - db.env