global:
  scrape_interval:     15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prod'
    metrics_path: "/api/v1/metrics"
    static_configs:
      - targets: ['prod:8000']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
